### ISSUE TITLE
Config variable names

### ISSUE THREAD

**Issue by Ventan00** [Ventan00/quanda#107]
How should we name variables in a shared config?
Should we follow https://github.com/Visual-Stylecop/Visual-StyleCop/wiki/SA1311 and use ThisTypeOfConfigVariables
or THIS_TYPE_OF_CONFIG_VARIABLES. I think the second option is more visible in the code, but is not following the standards

**Comment by pnarozniak** [comment]
In my opinion there is no point of "braking" the rules. So I would definitely go for ThisTypeOfConfigVariables.

**Comment by Patrykoss** [comment]
We can stick with Pascal case.
