### ISSUE TITLE
You can access login/register page when logged

### ISSUE THREAD

**Issue by Ventan00** [Ventan00/quanda#65]
![image](https://user-images.githubusercontent.com/56700157/129245023-fd82c66a-be7a-4db6-89c7-bf73dc18f8c3.png)
![image](https://user-images.githubusercontent.com/56700157/129245036-fe89f68c-4c38-47a5-8186-f9553ff80df7.png)
![image](https://user-images.githubusercontent.com/56700157/129245075-6411ff68-da59-4520-b4d6-b2dd16bc60eb.png)
As you can see from the examples - access to these pages is possible after logging in. This must be blocked.

**Comment by pnarozniak** [comment]
Should I redirect user to "/" page and display message telling him that he can't perform this operation while logged in?
@Ventan00

**Comment by Ventan00** [comment]
That is a good idea
