### ISSUE TITLE
Captcha randomly not rendering

### ISSUE THREAD

**Issue by Ventan00** [Ventan00/quanda#67]
![image](https://user-images.githubusercontent.com/56700157/129252655-694e217a-198a-4ca2-b912-d161331f95b7.png)
This is exception information I get I try to log in. Captcha is not loaded on page

**Comment by pnarozniak** [comment]
@Ventan00 
Can you tell when this exception occurred? Because I try everything and I can't hit on this exception.

**Comment by Ventan00** [comment]
I think it was on an older version, and now it has somehow been fixed by itself. I am closing this issue.

**Comment by Ventan00** [comment]
> @Ventan00
> Can you tell when this exception occurred? Because I try everything and I can't hit on this exception.

When switching between login and register page.
